### ISSUE TITLE
New "exclude_context" issue

### ISSUE THREAD

**Issue by keul** [plone/plone.portlet.collection#5]
In the last (minor :disappointed:) version a `exclude_context` feature has been added. This breaks every other add-ons that extends basic plone.portlet collection.

    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module ZPublisher.Publish, line 48, in call_object
      Module plone.app.portlets.browser.formhelper, line 54, in __call__
      Module zope.formlib.form, line 795, in __call__
      Module five.formlib.formbase, line 50, in update
      Module zope.formlib.form, line 776, in update
      Module zope.formlib.form, line 620, in success
      Module plone.app.portlets.browser.formhelper, line 71, in handle_save_action
      Module zope.formlib.form, line 901, in createAndAdd
      Module redturtle.portlet.collection.rtcollectionportlet, line 214, in create
    TypeError: __init__() got an unexpected keyword argument 'exclude_context'

Why the new `exclude_context` attribute is not a *class* attribute but only an instance attribute of the `Assignment`? I think that a class attribute can help in preventing this issue.

I'm testing the issue on a fresh Plone 4.3.4 with 2.1.x branch

**Comment by davisagli** [comment]
A class attribute would not prevent the add form from passing this new keyword argument to your constructor. I think you'll have to update your add-on to handle the new argument.

**Comment by keul** [comment]
@davisagli sorry I badly posted the issue mixing two argument. Of course every add-ons that extend default Assignment must upgrade (I found this a little annoying for a minor release, but acceptable).

But still: is right that this new attribute is the only one that isn't at class level?

Let's me make an example I just tested.

A new Plone site (now a 4.3.3) where I have plone.portlet.collection 2.1.5. There I added a new portlet collection.
After that I upgrade plone.portlet.collection to 2.1.6 and If I go in edit of the portlet I get this:

    2015-02-17 09:53:26 ERROR Zope.SiteErrorLog 1424163206.150.340606563527    http://localhost:8080/Plone/++contextportlets++plone.rightcolumn/col-col/edit
    Traceback (innermost last):
      Module ZPublisher.Publish, line 138, in publish
      Module ZPublisher.mapply, line 77, in mapply
      Module ZPublisher.Publish, line 48, in call_object
      Module plone.app.portlets.browser.formhelper, line 126, in __call__
      Module zope.formlib.form, line 795, in __call__
      Module five.formlib.formbase, line 50, in update
      Module zope.formlib.form, line 758, in update
      Module zope.formlib.form, line 833, in setUpWidgets
      Module zope.formlib.form, line 412, in setUpEditWidgets
      Module zope.schema._bootstrapfields, line 215, in get
    AttributeError: exclude_context

I blogged about this lot of years ago, but this seems still valid.
http://blog.keul.it/2011/04/plone-portlets-are-not-enemies-just.html

**Comment by davisagli** [comment]
You're right, it needs the class attribute. Added on master and the 2.1.x branch. /cc @rpatterson

**Comment by keul** [comment]
OK thanks, so I think this can be closed
